   const data = [
        {
            "title": "Lentera Jiwa",
            "date": "05/03/2023",
            "author": "Pdt. I Ketut Miasa.S.th.M.Div.",
            "verse": "Yoel 2:1-2, 12-17",
            "content": "Dalam bacaan hari ini dua kali penulis kitab Yoel menuliskan 'Tuhan menyesal'. Tentu pernyataan ini mengundang pertanyaan karena bagaimana mungkin Tuhan yang Maha Tahu itu bisa menyesal? Seolah-olah Tuhan tidak tahu apa yang akan terjadi. Tentu pernyataan tersebut perlu dipahami dengan tepat supaya kita tidak tersesat dalam pemikiran yang keliru.<br>Pernyataan 'Tuhan menyesal' ini dapat ditemukan beberapa kali di dalam Alkitab dan merupakan bentuk kiasan (figuratif) untuk menggambarkan perasaan Tuhan. Ada dua kondisi yang menggambarkan penyesalan Tuhan. Pertama Tuhan menyesal karena melihat kondisi manusia (umatNya) yang terus menerus berbuat dosa bahkan semakin jahat (Kejadian 6:6). Kedua Tuhan menyesal karena telah merancangkan penghukuman atas mereka saat melihat pertobatan yang sungguh-sungguh dari umatNya. Salah satunya kita temui dalam ayat 13 dan 14. Konteks bacaan hari ini adalah Tuhan berduka karena pemberontakan umatNya yang menyembah dan tunduk kepada dewa-dewa asing. Namun demikian Tuhan masih memberikan kesempatan agar mereka sadar dan bertobat. Pesan yang disampaikan melalui Yoel adalah Tuhan mengajak umatNya untuk menguji atau membuktikan sendiri apa yang dikatakanNya itu. Jika mereka sungguh-sungguh bertobat, Tuhan menyesal telah merancangkan penghukuman atas mereka dan Dia bersedia untuk membatalkannya.<br>Sekarang kita mengerti bahwa penyesalan Tuhan dalam bacaan hari ini merupakan pernyataan kiasan yang menggambarkan bahwa Tuhan bersedia untuk membatalkan hukuman yang telah dirancangkan ketika kita sungguh-sungguh bertobat kepadaNya. Semua karena kasihNya yang begitu besar atas kita. Walaupun demikian, Dia juga Tuhan yang adil dan tidak membiarkan diriNya di permainkan dengan terus menerus berbuat dosa. Saat waktuNya sudah genap hanya akan ada pengampunan bagi mereka yang bertobat atau penghukuman bagi mereka yang terus menerus mengeraskan hati. Oleh karena itu koyakkanlah hatimu dan berbaliklah kepada Tuhan (ayat 13). Dialah Tuhan yang penuh kasih, panjang sabar dan berlimpah kasih setiaNya. TanganNya senantiasa terbuka bagi setiap kita yang datang dengan pertobatan.<br>Tuhan Yesus Memberkati..."
        },
        {
            "title": "Lentera Jiwa",
            "date": "13/03/2023",
            "author": "Pdt. I Ketut Miasa.S.th.M.Div.",
            "verse": "Kejadian 13:1-7, 14-18",
            "content": "Kebijaksanaan Abraham terlihat dari bagaimana ia menyelesaikan persoalan dengan keponakannya sendiri. Ayat 3 menuliskan bahwa Abraham sangat kaya selain itu dia pun sudah tua (sangat senior) dan Lot adalah keponakannya. Lot diajak untuk ikut dengan Abraham. Istilahnya Lot menumpang pada Abraham. Namun saat terjadi konflik dan mereka harus berpisah, Abraham memberikan kesempatan pertama bagi Lot untuk memilih wilayah tempat tinggalnya. Kekayaan yang dimilikinya tidak membuat Abraham menjadi sombong dan sok berkuasa.<br>Abraham memilih untuk menyelesaikan persoalan dengan baik supaya hubungan persaudaraan tidak rusak hanya gara-gara harta. Berbeda sekali dengan konteks masyarakat hari ini dimana sesama saudara kandung, suami istri bahkan orang tua anak berkonflik hanya gara-gara harta warisan. Abraham walapun sangat kaya, tua dan berkuasa tetap menghormati serta mengasihi Lot.<br>Kebijaksanaan Abraham juga terlihat dari kepercayaannya kepada Tuhan sehingga tidak mempersoalkan dimanapun nanti dia akan menetap. Bagi Abraham yang penting bukanlah di mana dia akan tinggal tetapi apakah Tuhan besertanya atau tidak. Hal ini kemudian terbukti dimana Lot yang memilih wilayah subur tetapi kemudian hidupnya hancur karena mengikuti cara hidup orang yang ada disana. Nyaris tidak terselamatkan jika bukan karena Abraham memohon belas kasihan Tuhan.<br>Kita perlu menyadari bahwa dalam hidup ini penyertaan Tuhanlah yang menentukan segalanya bukan apa yang kita miliki, jabatan, relasi dan sebagainya. Penyertaan Tuhanlah yang mampu membuat padang gersang menjadi padang yang berumput hijau. Tuhan pasti akan menyertai jika kita taat melakukan kehendak dan berjalan di dalam rencanaNya. Oleh karena itu mari belajar untuk mengerti kehendak Tuhan dan setia berjalan di dalam rencanaNya. Pasti akan ada tantangan. Namun kita juga akan menemukan dan melihat pertolongan Tuhan tepat pada waktunya.<br>Tuhan Yesus Memberkati..."
        },
        {
            "title": "Lentera Jiwa",
            "date": "19/03/2023",
            "author": "Pdt. I Ketut Miasa.S.th.M.Div.",
            "verse": "Kejadian 15:1-12, 17-18",
            "content": "Tuhan mengulang kembali janjiNya kepada Abraham yang sudah hampir putus asa menunggu penggenapan janji tersebut. Abraham bahkan berpikir bahwa Eliezer (hamba Abraham) yang akan mewarisi harta miliknya. Tuhan menegaskan bahwa keturunan Abrahamlah yang akan mewarisi harta miliknya. Tuhan kemudian mengikat perjanjian dengan Abraham dengan cara berjalan melewati tengah-tengah potongan hewan dalam bentuk suluh berapi.<br>Pengikatan perjanjian dengan cara seperti ini merupakan cara yang lazim digunakan oleh orang pada jaman itu untuk mengikat perjanjian. Arti dari tindakan berjalan ini adalah jika orang yang melewati potongan hewan tersebut melanggar perjanjian maka dia akan mati sama seperti hewan yang terbelah itu. Biasanya yang membuat perjanjian dan berjalan itu adalah pihak yang lebih lemah. Namun dalam konteks Abraham justru Tuhanlah yang melakukannya. Apa maksud dari tindakan tersebut?<br>Tentu yang Tuhan lakukan bukan untuk menunjukkan bahwa Tuhan lebih rendah dari Abraham tetapi untuk menunjukkan kesungguhan Tuhan terhadap janjiNya. Tuhan menyakinkan Abraham bahwa perjanjian yang dibuat dengannya adalah perjanjian yang pasti akan digenapi. Tuhan yang memilih, memanggil, berjanji kepada Abraham dan Tuhan yang sama itu akan menggenapi janjiNya. Sepanjang sejarah kita mengetahui bahwa Tuhan adalah Allah yang menggenapi janjiNya.<br>Ketika manusia jatuh ke dalam dosa, Tuhan berjanji akan menyediakan seorang penebus (juruselamat) bagi kita (Kejadian 3:15). Hal itu digenapi dalam Yesus yang datang, mati dan bangkit. Bukti bahwa Tuhan setia terhadap janjiNya sudah terlalu nyata sehingga tidak ada alasan bagi kita untuk tidak mempercayaiNya. Tuhan pasti akan datang kembali. PengampunanNya pasti akan diberikan bagi setiap kita yang percaya kepadaNya. Kehidupan yang kekal itu pasti akan diberikan kepada setiap kita yang sungguh-sungguh mengikutiNya. Apakah kita mau mengikutiNya dengan sungguh-sungguh?<br>Tuhan Yesus Memberkati..."
        },
        {
            "title": "Lentera Jiwa",
            "date": "27/03/2023",
            "author": "Pdt. I Ketut Miasa.S.th.M.Div.",
            "verse": "Yosua 4:1-13",
            "content": "Ketaatan merupakan salah satu ciri atau karakater penting seorang pengikut Tuhan. Ketaatan terutama pada kehendakNya mendatangkan perkenanan dan penyertaan Tuhan dalam segala hal yang kita kerjakan. Salah satu contohnya kita temui dalam kisah ketika bangsa Israel menyeberangi Sungai Yordan. Penyeberangan ini merupakan proses mereka untuk menduduki tanah perjanjian.<br>Setelah selesai menyeberang, Tuhan pun memerintahkan Yosua untuk membangun tugu peringatan tersusun dari dua belas batu yang berasal dari tengah-tengah sungai Yordan tempat para imam berdiri. Lokasi tugu peringatan itu pun sudah Tuhan tentukan yaitu di tempat mereka bermalam atau di Gilgal (ayat 3). Yosua dengan taat melakukannya bahkan Yosua pun memerintahkan untuk membuat tugu yang kedua dengan lokasinya di tempat para imam berdiri atau di tengah-tengah Sungai Yordan (ayat 9).<br>Kedua tugu tersebut memiliki jumlah batu yang sama yaitu dua belas. Keduanya adalah sebuah peringatan kepada Bangsa Israel dan juga kita sebagai pengikutNya masa kini. Tugu yang pertama adalah peringatan akan kedahsyatan tangan Tuhan menuntun serta melepaskan Bangsa Israel. Sedangkan tugu yang kedua, salah satu penafsir menjelaskan bahwa tugu itu adalah simbol dari amarah atau murka Tuhan yang menenggelamkan atau menghancurkan orang-orang yang menolak untuk taat kepadaNya. Tugu yang pertama merupakan simbol dari 12 suku yang di ijinkan masuk ke tanah perjanjian sedangkan tugu yang kedua adalah simbol dari 12 suku yang binasa di padang gurun karena ketidaktaatan mereka.<br>Jadi kedua tugu ini memberikan pelajaran penting tentang ketaatan kepada Tuhan. Jika taat pada perintahNya maka tuntunan dan kelepasanlah yang akan kita dapatkan. Namun sebalilknya, ketidaktaatan mendatangkan murka Tuhan yang akan menenggelamkan dan membinasakan kita. Memang taat pada perintahNya itu tidaklah mudah karena terkadang bertentangan dengan kenyamanan atau pun dengan apa yang kita inginkan, menuntut pengorbanan terutama harga diri dan lain sebagainya. Namun ingatlah bahwa pilihan untuk taat atau tidak taat sangat menentukan hasil yang akan kita terima. Marilah kita memilih dengan bijak.<br>Tuhan Yesus Memberkati..."
        },
        {
            "title": "Lentera Jiwa",
            "date": "03/04/2023",
            "author": "Pdt. I Ketut Miasa.S.th.M.Div.",
            "verse": "2 Raja-Raja 4:1-7",
            "content": "Tuhan selalu menjagai dan memelihara hidup orang yang takut kepadaNya. Janda seorang nabi datang menemui Elisa mengadukan persoalan yang sedang dihadapinya. Suami dari janda ini telah mati dan dia adalah seorang yang takut akan Tuhan sepanjang hidupnya. Janda ini terlibat hutang dan akan kehilangan anaknya jika hutangnya tersebut tidak dibayarkan.<br>Bentuk pemeliharaan dan penjagaan Tuhan terlihat melalui hikmat yang Tuhan berikan kepada Elisa. Tuhan memerintahkan agar janda itu mengisi bejana-bejana kosong yang mereka pinjam dengan buli-buli berisi minyak, milik mereka satu-satunya (ayat 2-4). Sebuah permintaan yang aneh karena secara ukuran bejana itu lebih besar daripada buli-buli. Namun yang dituntut dari janda ini adalah iman yang teguh kepada Tuhan.<br>Permintaan itu diikuti sepenuhnya oleh janda ini. Hal tersebut menunjukkan kepasrahan janda ini kepada pimpinan Tuhan. Janda ini percaya dan melakukan tepat seperti yang diperintahkan kepadanya. Mujizat pun terjadi. Minyak dalam buli-buli mereka terus mengalir mengisi bejana-bejana yang ada hingga tidak tersedia lagi bejana yang kosong. Minyak itu kemudian di jual untuk membayar hutang dan sisanya untuk memenuhi kebutuhan mereka.<br>Setiap kita pasti menghadapi berbagai macam persoalan dalam hidup bahkan ada yang mungkin terlibat hutang sama seperti yang dihadapi oleh janda ini. Apa yang perlu kita lakukan? Jangan biarkan iman kita menjadi lemah. Tetaplah percaya kepada Tuhan. Temuilah orang yang tepat yaitu orang yang dewasa secara rohani sehingga kita bisa mendapatkan hikmat untuk mengetahui apa yang harus dilakukan. Kemudian lakukanlah dengan penuh ketaatan apa yang Tuhan perintahkan. Tuhan akan menyediakan pertolonganNya saat kita sungguh-sungguh berharap kepadaNya.<br>Tuhan Yesus Memberkati…",
        },
        {
            "title": "Lentera Jiwa",
            "date": "10/04/2023",
            "author": "Pdt. I Ketut Miasa.S.th.M.Div.",
            "verse": "Mazmur 118:1-2, 19-29",
            "content": "Mazmur 118 berada tepat di tengah Alkitab. Ada 594 pasal sebelum dan sesudah pasal 118. Pasal ini dibuka dengan ajakan untuk bersyukur atas kebaikan dan kasih setia Tuhan yang telah ditunjukkanNya. Dalam ayat 21 misalnya pemazmur mengatakan bahwa Tuhan telah menjawab doa dan menyelamatkannya.<br>Pada Mazmur ini pun terkandung nubuatan akan Yesus Sang Mesias. Kita menemukannya dalam ayat 22 'Batu yang dibuang oleh tukang-tukang bangunan telah menjadi batu penjuru'. Yesus sendiri mengutip ayat ini dalam pengajaranNya kepada para murid untuk menjelaskan bahwa diriNya akan di hancurkan (dibuang) melalui salib tetapi kemudian bangkit dan menjadi batu penjuru. Batu penjuru adalah batu yang digunakan oleh tukang bangunan sebagai patokan atau standar dari sebuah bangunan.<br>Yesus yang menjadi batu penjuru artinya Yesus menjadi patokan kita dalam menjalani hidup ini. Kita meniru atau menyerupai cara Yesus hidup di dunia ini yaitu dengan taat melakukan kehendak Bapa di Surga. Jadi jika kita menyimpulkan maksud dari pasal 118 ini adalah kita bersyukur atas kebaikan dan kasih setia Tuhan yang telah ditunjukkanNya dengan memberikan Yesus Kristus AnakNya yang Tunggal untuk menjadi Juruselamat. Cara kita bersyukur akan hal itu adalah dengan meniru atau mencontoh gaya hidup Yesus yang dengan penuh ketaatan melakukan kehendak Bapa di Surga.<br>Dengan demikian maka pasal ini pun relevan bagi kita para pengikutNya masa kini. Kita bukan hanya bersyukur dengan kata-kata pengagungan kepadaNya tetapi juga dengan taat melakukan apa yang menjadi kehendakNya. Kita bisa mengetahui kehendak Tuhan melalui persekutuan dan pembacaan FirmanNya. Ketaatan pada kehendakNya membuat hati, pikiran, motivasi serta karakter kita diubahkan menjadi semakin serupa dengan Kristus. Proses ini tidaklah mudah dan nyaman tetapi ingatlah bahwa ucapan syukur yang sejati adalah ucapan syukur yang disertai dengan ketaatan pada kehendakNya.<br>Tuhan Yesus Memberkati…",
        },
        {
            "title": "Lentera Jiwa",
            "date": "17/04/2023",
            "author": "Pdt. I Ketut Miasa.S.th.M.Div.",
            "verse": "Keluaran 14:10-31",
            "content": "Menarik untuk mempelajari kisah bagaimana Bangsa Israel menyeberangi laut mati. Mereka dalam kondisi yang terjepit. Di depan mereka ada laut sedangkan Firaun beserta pasukannya ada di belakang. Bangsa Israel yang ketakutan berseru kepada Musa. Dengan penuh iman Musa menenangkan serta meyakinkan mereka akan pertolongan Tuhan. Tetapi keanehan kita dapati pada ayat 15.<br>Di ayat 15, Tuhan bertanya mengapa Musa berseru-seru demikian kepadaNya. Sepertinya ada sesuatu antara ayat 14 dan 15 yang tidak tercatat. Sesuatu itu adalah Musa berdoa atau lebih tepatnya menyerukan ketakutannya kepada Tuhan. Namun jika kita memperhatikan ayat 15 mengapa seolah-olah Tuhan tidak berkenan dengan tindakan Musa? Bukankah pada saat takut sebaiknya kita datang pada Tuhan?<br>Penjelasan yang pertama adalah situasi yang mereka hadapi adalah seijin Tuhan. Mereka dalam sebuah perjalanan menuju ke tanah perjanjian yang Tuhan berikan. Tuhan bahkan memimpin sendiri umatNya melalui kehadiran Tiang Awan dan Tiang Api. Jadi seharusnya mereka tidak perlu takut karena pembelaan Tuhan pasti akan dinyatakan. Kedua bukankah Tuhan sudah menunjukkan bahwa Firaun dan Mesir bukan tandinganNya? Bukankah Tuhan sudah mempermainkan mereka dengan 10 tulah sehingga umatNya dapat keluar dari Mesir?<br>Kedua hal inilah yang Tuhan ingatkan kepada Musa dan juga kepada kita hari ini. Terkadang Tuhan mengijinkan masalah datang untuk menguji kekuatan iman kita kepadaNya. Selama kita berada pada rencana dan kehendakNya, Tuhan pasti akan menjagai serta memelihara. Kita perlu melangkah dengan iman yaitu melangkah di jalan yang Tuhan kehendaki. Dalam kasusnya Musa adalah melewati laut. Jadi penting bagi kita untuk mengetahui dan memastikan bahwa kita berada pada jalanNya Tuhan. Satu-satunya cara adalah dengan terus membangun hubungan denganNya, membaca FirmanNya sehingga kita semakin mengetahui pribadi Tuhan.<br>Tuhan YesusMemberkati…",
        },
        {
            "title": "Lentera Jiwa",
            "date": "29/04/2023",
            "author": "Pdt. I Ketut Miasa.S.th.M.Div.",
            "verse": "Yesaya 6:1-4",
            "content": "Pembacaan hari ini mengajarkan kita 2 hal. Pertama adalah mempercayai Tuhan dengan sepenuh hati. Hal ini bisa kita lihat dengan membandingkan pemerintahan manusia (Uzia) dengan pemerintahan Tuhan. Yesaya menyampaikan pesan Tuhan ini kepada umatNya di jaman pemerintahan Uzia. Uzia memerintah sebagai raja selama 50 tahun.<br>Waktu pemerintahan yang cukup panjang sebenarnya untuk ukuran manusia tetapi pemerintahan itu pun tetap akan berakhir. Oleh karena itu sia-sialah mengandalkan manusia ataupun yang lain selain Tuhan karena kekuasaan dan waktu mereka sangatlah terbatas. Hanya Tuhanlah yang kekal. Dia sudah ada dari dulu dan akan tetap ada selama-lamaNya. Dia tahu segalaNya dan pemilik segalaNya.<br>Kedua, sadarilah bahwa Tuhan yang kita sembah adalah Allah yang kudus. Tidak sembarang orang boleh menghadapNya. Kekudusan yang adalah karakteristik utama Tuhan terlihat jelas dalam ayat 2 dan 3. Serafim malaikat pelayan Tuhan harus menutup muka dan kaki mereka saat melayani Raja di atas segala raja. Tuhan itu kudus karena padaNya tidak ada ketidakbenaran. KekudusanNya seperti api yang menghanguskan membuat semua orang yang berdosa takut untuk berhadapan denganNya.<br>Bersyukurlah bahwa darah Yesus telah melayakkan kita untuk menghadap hadiratNya. Namun demikian bukan berarti selama di dunia ini kita boleh hidup sembarangan. Kita sedang berada dalam proses pengudusan. Oleh karena itu belajarlah untuk hidup berkenan kepada Tuhan dengan menjauhi apa yang menjadi laranganNya.<br>Tuhan Yesus Memberkati…"
        },
        {
            "title": "Lentera Jiwa",
            "date": "08/05/2023",
            "author": "Pdt. I Ketut Miasa.S.th.M.Div.",
            "verse": "Yehezkiel 11:1-25",
            "content": "Kita perlu berhati-hati dalam menjalani hidup ini terutama dalam hal memilih siapa yang kita dengarkan dan jadikan acuan. Bangsa Israel menjadi contoh bagi kita. Mereka disesatkan oleh para pemimpinnya sendiri yang mengabaikan peringatan dan kebenaran Tuhan. Mereka senang untuk mendengarkan nubuatan-nubuatan palsu para pemimpinnya. Akibatnya pembuanganlah yang mereka dapatkan.<br>Saat ini pun penyesatan masih terus terjadi. Bahkan akan semakin dahsyat menjelang kedatangan Tuhan yang kedua kali. Akan muncul orang-orang yang mengatasnamakan kebenaranNya tetapi apa yang mereka ajarkan tidak sesuai dengan kebenaran Alkitab. Mereka menggunakan kata-kata yang indah dan enak didengar oleh telinga. Pengajaran mereka adalah pengajaran yang jauh dari kebenaran, menyesatkan dan tidak membuat iman kita kuat kepadaNya.<br>Jika tidak berhati-hati maka kita pun bisa disesatkan oleh pengajaran mereka. Terutama pada saat kita sedang berhadapan dengan berbagai macam kesulitan dan tantangan hidup. Kita tergoda untuk mengikuti atau mempercayai apa yang mereka katakan karena ingin segara bisa terbebas. Namun saat apa yang di harapkan tidak terjadi, kita menjadi kecewa dan tidak percaya lagi kepada Tuhan.<br>Oleh karena itu sadarilah bahwa kita adalah orang-orang yang mudah sekali disesatkan. Bersandarlah senantiasa kepada anugerah dan kasih setiaNya. Jangan bersandar kepada pengertian kita sendiri. Mintalah agar Tuhan senantiasa berbelas kasihan atas kita dengan memberikan hati dan roh yang baru. Ingatlah bahwa kita perlu mempertahankan iman sampai pada kesudahannya. Hanya dengan iman lah kita akan bertemu dan tinggal bersama-sama denganNya dalam kekekalan.<br>Tuhan Yesus Memberkati…"
        },
        {
            "title": "Lentera Jiwa",
            "date": "15/05/2023",
            "author": "Pdt. I Ketut Miasa.S.th.M.Div.",
            "verse": "Kisah Para Rasul 9:36-43",
            "content": "Petrus memperlihatkan kuasa atau otoritas yang besar saat membangkitkan Dorkas. Kuasanya itu berasal Roh Kudus yang menyertai Petrus. Ini merupakan janji yang Yesus katakan sebelum terangkat ke Surga. Setiap orang yang dipilihNya untuk mengabarkan Injil, mereka akan disertai dengan kuasa yang besar untuk melakukan tanda-tanda ajaib.<br>Tentu tujuan dari tanda-tanda ajaib ini adalah untuk menyatakan kekuasaan, kedaulatan dan kemuliaan Tuhan. Kita tahu bahwa hidup dan mati ada pada Tuhan. Manusia tidak akan sanggup melakukannya. Jadi, ketka Petrus mampu membangkitkan Dorkas atau mendatangkan kematian bagi Ananias dan Safira (Kisah Para Rasul 5:1-11) semua itu adalah untuk membuktikan bahwa Tuhan beserta dengannya.<br>Kuasa itu pun menyertai Dorkas. Dorkas seorang wanita yang menjadi murid Kristus dan menggunakan talenta yang dimilikinya untuk melayani orang lain. Sebagai seorang penjahit dia membuatkan baju dan jubah bagi orang-orang yang membutuhkan. Apa yang dilakukannya mungkin tidak 'sehebat' Petrus tetapi yang pasti mengubahkan hidup orang yang menerimanya.<br>Petrus dan Dorkas adalah orang-orang biasa namun disertai oleh Tuhan yang memiliki kuasa yang luar biasa. Tuhan yang sama itu pun menyertai kita saat ini. Sebagai umat yang telah ditebusNya kita pun memiliki kuasa yang sama untuk membawa orang kepada kebenaran melalui apa yang kita kerjakan. Janganlah berdiam diri. Kobarkanlah api Roh Kudus yang telah ada dalam diri kita. Mungkin tidak semua kita adalah Petrus tetapi yang pasti kita bisa seperti Dorkas, melayani Tuhan dengan seluruh talenta yang Tuhan berikan kepada kita.<br>Tuhan Yesus Memberkati…"
        },
        {
            "title": "Lentera Jiwa",
            "date": "07/06/2023",
            "author": "Pdt. I Ketut Miasa.S.th.M.Div.",
            "verse": "Yehezkiel 11:14-25",
            "content": "Hati merupakan pusat kendali manusia. Disanalah terdapat pikiran, perasaan dan kehendak yang melahirkan keputusan demi keputusan dan bermuara pada tindakan. Jika hati kita baik maka apa yang keluar melalui hidup kita pun akan baik. Sebaliknya jika hati kita dipenuhi oleh berbagai macam kecemaran maka hal-hal yang buruklah yang akan keluar melalui hidup kita.<br>Dalam ayat 19 dikatakan bahwa Tuhan akan memberikan umatNya hati yang baru, yang mau tunduk kepada segala perintah Tuhan serta dengan penuh ketaatan untuk melakukanNya. Hati umatNya yang lama telah rusak oleh dosa sehingga segala keputusan, tindakan maupun perkataan mereka semuanya menyimpang dari kebenaran yang telah Tuhan tetapkan. Tak heran jika kemudian mereka berada di pembuangan.<br>Sebagai pengikutNya pada jaman ini, Tuhan menganugerahkan kepada kita '‘'hati yang baru'’', yaitu hati yang dapat mengerti dan mengakui karya penebusan Yesus di kayu salib. Tuhan memilih dan menetapkan kita untuk percaya kepadaNya. Tanpa anugerahNya tidak mungkin kita bisa percaya. Yohanes 15:16 mengatakan bukan kamu yang memilih Aku tetapi Aku yang memilih kamu.<br>Tuhan pun menganugerahkan hati yang baru agar setiap kita sebagai pengikutNya memiliki kemampuan untuk taat pada setiap perintahNya. Oleh karena itu kita perlu belajar untuk menjaga hati ini dengan berusaha untuk mematikan keinginan daging yang berusaha menguasai hati kita. Pikirkanlah semua yang benar, mulia, adil, suci, manis, sedap di dengar, kebajikan dan yang patut dipuji. Jika hati kita dipenuhi oleh hal-hal tersebut maka yang baik itu pulalah yang akan keluar melalui hidup kita.<br>Tuhan Yesus Memberkati…"
        },
        {
            "title": "Lentera Jiwa",
            "date": "14/06/2023",
            "author": "Pdt. I Ketut Miasa.S.th.M.Div.",
            "verse": "Amsal 7:1-4",
            "content": "Salah satu dosa yang mengintai orang muda dan tak jarang menjatuhkan mereka adalah dosa seksual. Salomo menyadari hal ini dan menasehati anak-anaknya yang masih muda, kurang pengalaman dan cenderung terbawa hawa nafsu agar mereka dapat menjaga diri sehingga tidak jatuh ke dalam dosa itu. Jadi ayat 1-4 merupakan hal yang perlu dilakukan sebagai orang muda untuk menghadapi godaan seksual.<br>Nasihat Salomo ini tentu berkaitan dengan bagian sebelumnya yaitu pada pasal 6:20-35 yang diberi judul oleh LAI 'Nasihat tentang Perzinahan'. Salomo menitik beratkan nasehatnya pada apa yang mengisi hati kita yang merupakan pusat kendali manusia. Inti utama dari nasihat yang Salomo ajarkan adalah kemampuan untuk mengendalikan diri dengan senantiasa mengingat akan segala yang telah dikatakanNya.<br>Godaan seks atau perzinahan ini bisa menimpa siapa saja, tidak peduli usia, latar belakang maupun tingkat kerohanian. Jika tidak berhati-hati dan tidak mengendalikan diri maka mereka sedang membawa diri mereka sendiri kepada kehancuran. Kehancuran gambar diri, masa depan dan jika dilakukan oleh pasangan yang sudah menikah adalah kehancuran dalam rumah tangga mereka. Bahkan dampak yang lebih parah lagi adalah kehilangan keselamatan karena 'terpaksa' menikah dengan orang yang berbeda iman akibat hamil.<br>Nasihat ini perlu menjadi perhatian bagi diri sendiri dan perlu kita ajarkan juga kepada anak-anak. Seks itu indah jika dilakukan dalam koridor pernikahan dengan pasangan yang tepat (berasal dari Tuhan). Oleh karena itu belajarlah mengendalikan diri dengan selalu mengingat akan apa yang Tuhan perintahkan. Jika kita sudah terlanjur jatuh, segeralah bertobat dan kembali kepada Tuhan. PengampunanNya tersedia dan pasti akan diberikan kepada setiap orang yang sungguh-sungguh datang dalam pertobatan. Jangan pernah merasa diri kuat karena setiap kita dapat jatuh pada dosa ini.<br>Tuhan Yesus Memberkati…"
        },
        {
            "title": "Lentera Jiwa",
            "date": "06/07/2023",
            "author": "Pdt. I Ketut Miasa.S.th.M.Div.",
            "verse": "2 Raja-Raja 1:1-17",
            "content": "Sebelum hukuman terhadap Raja Ahazia dijatuhkan, Tuhan terlebih dahulu memperingatkannya melalui Elia. Tuhan bertujuan untuk menyadarkan Ahazia bahwa perbuatannya untuk meminta petunjuk kepada Ba’al Zebub adalah salah. Ahazia sendiri hidup melakukan kejahatan dan terlibat dalam penyembahan berhala mengikuti perbuatan Yerobeam bin Nebat.<br>Tuhan masih memberikan kesempatan bagi Ahazia untuk bertobat walaupun sudah sepantasnya ia menerima hukuman. Namun, Ahazia menolak kesempatan yang Tuhan berikan. Dalam kondisi sakit Ahazia masih tetap mengeraskan hatinya untuk bertobat dan tidak mau mendengarkan peringatan Tuhan. Hal ini membuktikan bahwa dosa mengakibatkan manusia tidak mencari Tuhan.<br>Ada beberapa pelajaran yang dapat kita ambil dari kisah Ahazia bahwa tidak semua orang mau meresponi anugerah Tuhan itu dengan tepat seperti yang dikehendakiNya. Ahazia tetap mengikuti jalan pemikiran yang salah walaupun Tuhan sudah jelas mengingatkannya. Dosa telah mengakibatkan hati Ahazia menjadi keras, gelap dan bodoh. Pilihan Ahazia bukan hanya mendapatkan penderitaan di akhir hidupnya tetapi juga membawa dia kepada kebinasaan kekal.<br>Apakah pertobatan selalu membawa kesembuhan atau membawa kelepasan dari penderitaan yang kita hadapi? Belum tentu bahkan mungkin sekali jawabannya tidak. Tetapi ada suatu pengharapan bahwa pertobatan membuat Tuhan kembali lagi berkenan atas kita. Sekalipun penderitaan membawa kepada kematian tetapi tidak membawa pada kebinasaan kekal. Jadi jika hari ini Tuhan menegur kita jangan keraskan hati. Carilah atau mendekatlah kepadaNya selama Ia masih berkenan untuk ditemui. Tidak ada gunanya segala hal yang kita dapatkan di dunia ini tetapi kehilangan keselamatan yang kekal.<br>Tuhan Yesus Memberkati…"
        },
        {
            "title": "Lentera Jiwa",
            "date": "29/06/2023",
            "author": "Pdt. I Ketut Miasa.S.th.M.Div.",
            "verse": "Ester 2:19-3:6",
            "content": "Ada 2 tokoh yang kita pelajari dari bacaan hari ini yaitu Mordekhai dan Haman.<br>1.	Mordekhai adalah orang yang fokus hidupnya melakukan kehendak Tuhan dengan taat. Tuhan yang memanggil dan menetapkannya menjadi salah satu pegawai raja. Mordekhai tahu ada suatu rencana khusus yang Tuhan tetapkan. Oleh karena itu ketika kebaikannya tidak di hargai, dia tidak kecewa karena tahu bahwa apa yang dilakukannya adalah untuk Tuhan bukan untuk manusia. Tuhanlah yang akan mencatat dan memberikan upah kepadanya.<br>2.	Haman adalah orang yang fokus hidupnya memuaskan hawa nafsu. Baginya jabatan, harta yang banyak, pengaruh serta penghormatan dari orang lain merupakan sesuatu yang wajib dia dapatkan serta pertahankan. Kebencian yang telah menguasai hidupnya membuat Haman tidak merasa bersalah ketika merancangkan rencana untuk membinasakan orang Yahudi. Dia mengejar kenikmatan sesaat di dunia ini.<br>Itulah perbedaan antara orang benar dan orang fasik. Orang fasik akan terus menerus mencari penghargaan dan pengakuan manusia. Dia akan merasa 'terganggu' jika hal itu tidak didapatkannya. Sebaliknya orang yang fokus melakukan kehendak Tuhan dia tidak kecewa, sakit hati ataupun mundur sekalipun tidak mendapatkan penghargaan yang seharusnya diterima. Dia tetap melakukan apa yang menjadi tanggung jawabnya dengan sepenuh hati.<br>Sikap seperti Mordekhai ini lah yang perlu kita teladani. Kita dipanggil, dipersiapkan dan ditetapkan Tuhan untuk melakukan tugas tertentu sesuai dengan kehendakNya. Jadi tanggung jawab utama kita adalah kepada Tuhan. Pemahaman ini seharusnya mendasari seluruh tindakan kita dimana pun dan dengan peran apa pun yang kita miliki.<br>Saat kita bekerja, bekerjalah sebaik-baiknya dengan memberikan hasil yang terbaik seperti untuk Tuhan dan bukan manusia. Demikian pula saat kita ada di sekolah, pelayanan maupun di dalam keluarga. Kita tidak mencari pujian manusia, tidak sakit hati ketika dikecewakan, tidak tersinggung ketika kesalahan kita ditegur, tidak menjadi batu sandungan dalam perkataan maupun perbuatan, displin dengan waktu (tidak suka terlambat), memegang komitmen dalam segala hal. Itulah beberapa hal yang dapat kita lakukan. Bersediakah?<br>Tuhan Yesus Memberkati…"
        },
    ]

export const getDataPemuda = () => {
    return [
        {
            "name": "Ratson Endy Dubulie",
            "alias": "acon",
            "birth_date": "10/22/2001",
            "email": "ratsonendy@gmail.com"
        },
        {"name":"Elliandro eggi darmawan","alias":"Andro","birth_date":"3/20/2007","email":"Elliandroandro@gmail.com"},
        {"name":"I Komang arya hizkia Adi Wiryawan","alias":"Arya","birth_date":"10/23/2007","email":"aryaceriwis005@gmail.com"},
        {"name":"Dika Aurelya Aleandra Taroreh","alias":"Aurel","birth_date":"10/12/2002","email":"aurelyataroreh@gmail.com"},
        {"name":"Bastian Adhi Ningrat Siswandi","alias":"Babas","birth_date":"06/09/1997","email":"bastianadhi39@gmail.com"},
        {"name":"Deffrand Farera","alias":"Bepa","birth_date":"2/20/2004","email":"hideffrand@gmail.com"},
        {"name":"Chelsea Olivia marie","alias":"Chelsea","birth_date":"8/24/2006","email":"Oliviamariechelsea@gmail.com"},
        {"name":"Daniel christian Taroreh","alias":"Dany","birth_date":"04/04/2007","email":"@danielctaroreh04"},
        {"name":"Chintya Devi Ambarwati","alias":"Devi","birth_date":"1/24/2005","email":"chintyadva@gmail.com"},
        {"name":"Editha Pramesti","alias":"Ditha","birth_date":"2/27/2004","email":"edithapramesti@gmail.com"},
        {"name":"Adam Evan Pramudita","alias":"Evan","birth_date":"11/05/2004","email":"adamevan171@gmail.com"},
        {"name":"Given Majesty Seo","alias":"Given","birth_date":"01/06/2008","email":"givenmajesty@gmail.com"},
        {"name":"Grace Indri Samantha Dubulie","alias":"Grace / Ge / Ges","birth_date":"2/21/1996","email":"Gracesmnth@gmail.com"},
        {"name":"fransisca putri agustin wijaya","alias":"icha","birth_date":"3/25/2009","email":"-"},
        {"name":"Indra Putra Pamungkas","alias":"Indra","birth_date":"04/11/1996","email":"indraputra560.ip@gmail.com"},
        {"name":"Kelly Amadea Cahyarini","alias":"Kelly","birth_date":"09/08/2009","email":"amadeacahyarini@gmail.com"},
        {"name":"Merry Theressa Papalangi","alias":"Merry","birth_date":"01/08/2007","email":"merrytheressa@gmail.com"},
        {"name":"Nadya adonia pai","alias":"Nadya","birth_date":"10/23/2007","email":"adonianadya@gmail.com"},
        {"name":"Priska Aprilla","alias":"Priska","birth_date":"4/27/1997","email":"Priska.desember@gmail.com"},
        {"name":"Brian David Tsang","alias":"Rian/Brian/David","birth_date":"04/10/2004","email":"briangamora37@gmail.com"},
        {"name":"titus anjora yohan febrian","alias":"titus, ntus, tit titit","birth_date":"2/22/2003","email":"titusanjora37@gmail.com"},
        {"name":"Alexander Victory Evrian Saputra","alias":"Vito","birth_date":"11/27/2002","email":"alexandersaputra8@gmail.com"},
        {"name":"yofindha augusta","alias":"yofin","birth_date":"02/08/2005","email":"yofindhacantik@gmail.com"}
    ]
}